apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: grafana-agent-logs
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/version: v0.33.2
    helm.sh/chart: grafana-agent-0.14.0
  name: grafana-agent-logs
  namespace: monitoring
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: grafana-agent-logs
      app.kubernetes.io/name: grafana-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: grafana-agent-logs
        app.kubernetes.io/name: grafana-agent
    spec:
      containers:
      - args:
        - run
        - /etc/agent/config.river
        - --storage.path=/tmp/agent
        - --server.http.listen-addr=0.0.0.0:80
        env:
        - name: AGENT_MODE
          value: flow
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        envFrom:
        - secretRef:
            name: grafana-agent-logs-env
        image: grafana/agent:v0.33.2
        imagePullPolicy: IfNotPresent
        name: grafana-agent
        ports:
        - containerPort: 80
          name: http-metrics
        - containerPort: 12347
          name: faro
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/agent
          name: config
      dnsPolicy: ClusterFirst
      serviceAccount: grafana-agent-logs
      volumes:
      - configMap:
          name: grafana-agent-logs-config
        name: config
