apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: 0.13.2
    helm.sh/chart: external-dns-1.12.1
  name: external-dns
  namespace: networking
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-dns
      app.kubernetes.io/name: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: external-dns
        app.kubernetes.io/name: external-dns
    spec:
      containers:
      - args:
        - --log-level=info
        - --log-format=text
        - --interval=1m
        - --source=service
        - --source=ingress
        - --policy=upsert-only
        - --registry=txt
        - --provider=cloudflare
        - --source=ingress
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: cloudflare-token
              name: external-dns-cloudflare-token
        image: registry.k8s.io/external-dns/external-dns:v0.13.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: external-dns
        ports:
        - containerPort: 7979
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
      securityContext:
        fsGroup: 65534
      serviceAccountName: external-dns
