apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    tanka.dev/namespaced: "false"
  name: letsencrypt
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: cloudflare-token
            name: cert-manager-cloudflare-token
