apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  annotations:
    tanka.dev/namespaced: "false"
  name: onepassword
spec:
  provider:
    onepassword:
      auth:
        secretRef:
          connectTokenSecretRef:
            key: token
            name: onepassword
            namespace: security
      connectHost: http://onepassword-connect.security.svc.cluster.local:8080
      vaults:
        Colorful Pandas: 1
