apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-cloudflare-token
  namespace: security
spec:
  data:
  - remoteRef:
      key: Cloudflare
      property: credential
    secretKey: cloudflare-token
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
