apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: colorful-pandas-env
  namespace: default
spec:
  data:
  - remoteRef:
      key: Neon main
      property: url
    secretKey: DB_URL
  - remoteRef:
      key: Colorful Pandas
      property: SECRET_KEY_BASE
    secretKey: SECRET_KEY_BASE
  - remoteRef:
      key: Colorful Pandas
      property: LIVEVIEW_SIGNING_SALT
    secretKey: LIVEVIEW_SIGNING_SALT
  - remoteRef:
      key: Colorful Pandas
      property: HONEYCOMB_API_KEY
    secretKey: HONEYCOMB_API_KEY
  - remoteRef:
      key: Colorful Pandas
      property: HONEYCOMB_DATASET
    secretKey: HONEYCOMB_DATASET
  - remoteRef:
      key: GitHub OAuth
      property: username
    secretKey: GITHUB_CLIENT_ID
  - remoteRef:
      key: GitHub OAuth
      property: credential
    secretKey: GITHUB_CLIENT_SECRET
  - remoteRef:
      key: Google OAuth
      property: username
    secretKey: GOOGLE_CLIENT_ID
  - remoteRef:
      key: Google OAuth
      property: credential
    secretKey: GOOGLE_CLIENT_SECRET
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
