apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  labels:
    app.kubernetes.io/component: contour
    app.kubernetes.io/instance: contour
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: contour
    helm.sh/chart: contour-12.1.1
  name: public
  namespace: networking
spec:
  controller: projectcontour.io/networking/contour-contour
