apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/version: v0.9.0
    helm.sh/chart: external-secrets-0.9.0
  name: external-secrets-leaderelection
  namespace: security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-secrets-leaderelection
subjects:
- kind: ServiceAccount
  name: external-secrets
  namespace: security
