apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: contour
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: contour
    helm.sh/chart: contour-12.1.1
  name: contour-contour
  namespace: networking
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
