apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: grafana-agent
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/version: v0.34.2
    helm.sh/chart: grafana-agent-0.16.0
  name: grafana-agent
  namespace: monitoring
