apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/version: v0.9.1
    external-secrets.io/component: webhook
    helm.sh/chart: external-secrets-0.9.1
  name: external-secrets-webhook
  namespace: security
