apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: colorful-pandas-pr-275
    app.kubernetes.io/name: colorful-pandas-pr-275
  name: colorful-pandas-pr-275-headless
  namespace: default
spec:
  clusterIP: None
  ports: []
  selector:
    app.kubernetes.io/instance: colorful-pandas-pr-275
    app.kubernetes.io/name: colorful-pandas-pr-275
