apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: connect
    app.kubernetes.io/instance: onepassword-connect
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.0
    helm.sh/chart: connect-1.11.0
  name: onepassword-connect
  namespace: security
spec:
  ports:
  - name: connect-sync
    port: 8081
  - name: connect-api
    port: 8080
  selector:
    app: onepassword-connect
  type: NodePort
