apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: grafana-agent-logs
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/version: v0.33.2
    helm.sh/chart: grafana-agent-0.14.0
  name: grafana-agent-logs
  namespace: monitoring
spec:
  ports:
  - name: http-metrics
    port: 80
    protocol: TCP
    targetPort: 80
  - name: faro
    port: 12347
    protocol: TCP
    targetPort: 12347
  selector:
    app.kubernetes.io/instance: grafana-agent-logs
    app.kubernetes.io/name: grafana-agent
  type: ClusterIP
