apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: colorful-pandas-pr-275
    app.kubernetes.io/name: colorful-pandas-pr-275
  name: colorful-pandas-pr-275
  namespace: default
spec:
  ports:
  - name: server-http
    port: 4000
    targetPort: 4000
  selector:
    app.kubernetes.io/instance: colorful-pandas-pr-275
    app.kubernetes.io/name: colorful-pandas-pr-275
