apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: contour
    app.kubernetes.io/instance: contour
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: contour
    helm.sh/chart: contour-12.1.1
  name: contour-contour
  namespace: networking
