apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: grafana-agent
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/version: v0.34.2
    helm.sh/chart: grafana-agent-0.16.0
  name: grafana-agent
  namespace: monitoring
spec:
  ports:
  - name: http-metrics
    port: 80
    protocol: TCP
    targetPort: 80
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app.kubernetes.io/instance: grafana-agent
    app.kubernetes.io/name: grafana-agent
  type: ClusterIP
