apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: colorful-pandas
    app.kubernetes.io/name: colorful-pandas
  name: colorful-pandas-headless
  namespace: default
spec:
  clusterIP: None
  ports: []
  selector:
    app.kubernetes.io/instance: colorful-pandas
    app.kubernetes.io/name: colorful-pandas
