apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: 0.13.2
    helm.sh/chart: external-dns-1.12.1
  name: external-dns
  namespace: networking
spec:
  ports:
  - name: http
    port: 7979
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/name: external-dns
  type: ClusterIP
