apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/part-of: cilium
    tanka.dev/environment: 439e2fd20d1bf711c47badca8952d4305eef138178fb3ea9
  name: cilium-config-agent
  namespace: networking
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
