apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: contour
    app.kubernetes.io/instance: contour
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: contour
    helm.sh/chart: contour-12.1.0
    tanka.dev/environment: 439e2fd20d1bf711c47badca8952d4305eef138178fb3ea9
  name: contour-contour
  namespace: networking
