compile-platform:
  - clusters/lib/**/*.libsonnet
  - clusters/lib/chartfile.yaml
  - clusters/platform/**/spec.json
  - clusters/platform/**/*.{jsonnet, libsonnet}

colorful-pandas: &colorful-pandas
  - colorful-pandas/**

test-colorful-pandas:
  - *colorful-pandas
  - .tool-versions

deploy-colorful-pandas:
  - *colorful-pandas

handbook: &handbook
  - handbook/**

deploy-handbook:
  - *handbook
