tanka:
  - clusters/lib/**/*.libsonnet
  - clusters/lib/chartfile.yaml
  - clusters/**/spec.json
  - clusters/**/*.{jsonnet, libsonnet}
  # These are handled by other workflows.
  - '!clusters/platform/default/colorful-pandas.jsonnet'
  - '!clusters/platform/docs/handbook.jsonnet'
