VERSION 0.7

ARG --global ELIXIR_BASE=hexpm/elixir:1.15.2-erlang-26.0.2-alpine-3.18.2
ARG --global DEPLOY_BASE=alpine:3.18.2

setup-base:
  FROM $ELIXIR_BASE

  RUN apk add --no-cache build-base git

  ENV ELIXIR_ASSERT_TIMEOUT=10000

  WORKDIR /colorful-pandas

  COPY mix.exs mix.lock .

  RUN mix do local.rebar --force, \
             local.hex --force
  RUN mix deps.get

compile:
  FROM +setup-base

  ARG ENV=test
  ENV MIX_ENV=$ENV

  RUN mix deps.compile

  COPY --dir config lib ./

  RUN mix compile --warnings-as-errors

test-image:
  FROM +compile --ENV=test

  COPY --dir priv test .

test:
  FROM earthly/dind:alpine

  RUN apk add postgresql-client

  COPY docker-compose.test.yml .

  WITH DOCKER \
      --compose docker-compose.test.yml \
      --load colorful-pandas:latest=+test-image
    RUN while ! pg_isready --host=localhost --port=5432 --username=postgres; do sleep 1; done ;\
      docker run --network host colorful-pandas mix ecto.create && \
      docker run --network host colorful-pandas mix ecto.migrate && \
      docker run --network host colorful-pandas mix test
  END

lint:
  FROM +compile --ENV=test

  COPY .credo.exs .formatter.exs .sobelow-conf .

  RUN mix deps.unlock --check-unused
  RUN mix hex.audit
  RUN mix format --check-formatted
  RUN mix credo
  RUN mix excellent_migrations.check_safety
  RUN mix sobelow --config

release:
  FROM +compile --ENV=prod

  COPY --dir assets rel priv .

  RUN mix do tailwind.install --if-missing, \
              esbuild.install --if-missing
  RUN mix do tailwind default --minify, \
            esbuild default --minify, \
            phx.digest
  RUN mix release colorful_pandas

  SAVE ARTIFACT _build/prod/rel/colorful_pandas

deploy:
  ARG --required VERSION
  ARG HOME=/opt/colorful-pandas

  FROM $DEPLOY_BASE

  RUN apk add --no-cache libstdc++ ncurses openssl && \
    adduser --system --shell /bin/false --home ${HOME} colorful-pandas

  WORKDIR /colorful-pandas
  USER colorful-pandas

  COPY --chown=colorful-pandas:0 +release/colorful_pandas .

  CMD ["/colorful-pandas/bin/server"]

  SAVE IMAGE --push ghcr.io/panda-den/colorful-pandas:$VERSION

update-buildcache:
  BUILD +test
  BUILD +lint
  BUILD +release
