name: "Compile environment"
description: "Compiles an environment using Tanka"
inputs:
  cluster:
    description: "Cluster to compile"
    required: true
  env:
    description: "Environment inside cluster to compile"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Jsonnet
      uses: kobtea/setup-jsonnet-action@1ba74f3571a59047dd4c5b8cb365bd3656f88e2a # v1
    # TODO: make this a proper action
    - name: Setup Tanka
      shell: bash
      run: |
        curl -L https://github.com/grafana/tanka/releases/download/v0.25.0/tk-linux-amd64 --output tk
        chmod +x tk
    - name: Install dependencies
      shell: bash
      run: jb install
    - name: Compile manifests
      shell: bash
      run: |
        mkdir -p ${{ inputs.cluster }}/compiled/${{ inputs.env }}
        tk export ${{ inputs.cluster }}/compiled/${{ inputs.env }} ${{ inputs.cluster }}/${{ inputs.env }} --merge-strategy replace-envs
