apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: handbook
    app.kubernetes.io/name: handbook
    tanka.dev/environment: 95f2e5977737602092bf0877799bea7da9b9d31f0678674c
  name: handbook
  namespace: docs
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: handbook
      app.kubernetes.io/name: handbook
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: handbook
        app.kubernetes.io/name: handbook
    spec:
      containers:
      - image: ghcr.io/cschmatzler/handbook:23.6.21-06e98d6
        name: handbook
        ports:
        - containerPort: 3000
          name: http
