apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: Helmraiser
    tanka.dev/environment: 8f414366f31d43444fdc780a19d124ba4288640390afcba2
  name: cilium-operator
  namespace: networking
