apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: hubble-peer
    app.kubernetes.io/part-of: cilium
    k8s-app: cilium
    tanka.dev/environment: 439e2fd20d1bf711c47badca8952d4305eef138178fb3ea9
  name: hubble-peer
  namespace: networking
spec:
  internalTrafficPolicy: Local
  ports:
  - name: peer-service
    port: 443
    protocol: TCP
    targetPort: 4244
  selector:
    k8s-app: cilium
