apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    tanka.dev/environment: a916120a6ded3ca7c01e6c3f52c2381957a38d80ebdc2cce
  name: cert-manager-cloudflare-token
  namespace: security
spec:
  data:
  - remoteRef:
      key: Cloudflare
      property: credential
    secretKey: cloudflare-token
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
