apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/version: v0.8.3
    helm.sh/chart: external-secrets-0.8.3
    tanka.dev/environment: a916120a6ded3ca7c01e6c3f52c2381957a38d80ebdc2cce
  name: external-secrets-leaderelection
  namespace: security
rules:
- apiGroups:
  - ""
  resourceNames:
  - external-secrets-controller
  resources:
  - configmaps
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
  - patch
