apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/version: v0.8.1
    helm.sh/chart: external-secrets-0.8.1
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    tanka.dev/environment: a916120a6ded3ca7c01e6c3f52c2381957a38d80ebdc2cce
  name: external-secrets-edit
rules:
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  - secretstores
  - clustersecretstores
  - pushsecrets
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
