apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
    helm.sh/hook-weight: "1"
  labels:
    app.kubernetes.io/instance: onepassword-connect
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.0
    helm.sh/chart: connect-1.11.0
    tanka.dev/environment: a916120a6ded3ca7c01e6c3f52c2381957a38d80ebdc2cce
  name: onepassword-connect-health-check
  namespace: security
spec:
  containers:
  - command:
    - curl
    - http://onepassword-connect:8080/health
    image: curlimages/curl
    name: curl
  restartPolicy: Never
