apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/version: v0.8.1
    helm.sh/chart: external-secrets-0.8.1
    tanka.dev/environment: a916120a6ded3ca7c01e6c3f52c2381957a38d80ebdc2cce
  name: external-secrets-webhook
  namespace: security
