apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: Helmraiser
    tanka.dev/environment: 93194c0ca0c3d273c6a9178aff091156fe38ce5c8c5d92fb
  name: hcloud-cloud-controller-manager
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: hcloud-ccm
      app.kubernetes.io/name: hcloud-cloud-controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: hcloud-ccm
        app.kubernetes.io/name: hcloud-cloud-controller-manager
    spec:
      containers:
      - command:
        - /bin/hcloud-cloud-controller-manager
        - --allow-untagged-cloud
        - --cloud-provider=hcloud
        - --leader-elect=false
        - --route-reconciliation-period=30s
        - --allocate-node-cidrs=true
        - --cluster-cidr=10.244.0.0/16
        env:
        - name: HCLOUD_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: hcloud
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HCLOUD_NETWORK
          valueFrom:
            secretKeyRef:
              key: network
              name: hcloud
        image: hetznercloud/hcloud-cloud-controller-manager:v1.15.0
        name: hcloud-cloud-controller-manager
        ports:
        - containerPort: 8233
          name: metrics
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
      dnsPolicy: Default
      hostNetwork: true
      priorityClassName: system-cluster-critical
      serviceAccountName: cloud-controller-manager
      tolerations:
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
