apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: Helmraiser
    tanka.dev/environment: 93194c0ca0c3d273c6a9178aff091156fe38ce5c8c5d92fb
  name: cloud-controller-manager
  namespace: kube-system
