name: "Compile environments"
description: "Compiles all environments for a cluster"
inputs:
  cluster:
    description: "Cluster to compile"
    required: true
  tanka-version:
    description: "Tanka version"
    required: false
    default: 0.25.0
  helm-version:
    description: "Helm version"
    required: false
    default: 3.12.1
runs:
  using: "composite"
  steps:
    - name: Setup Jsonnet
      uses: kobtea/setup-jsonnet-action@1ba74f3571a59047dd4c5b8cb365bd3656f88e2a # v1
    # TODO: make this a proper action
    - name: Setup Tanka
      shell: bash
      run: |
        curl -L https://github.com/grafana/tanka/releases/download/v${{ inputs.tanka-version }}/tk-linux-amd64 --output ${{ github.action_path }}/tk
        chmod +x ${{ github.action_path }}/tk
        echo ${{ github.action_path }} >> $GITHUB_PATH
    - name: Setup Helm
      uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3
      with:
        version: ${{ inputs.helm-version }}
    - name: Install dependencies
      shell: bash
      working-directory: clusters/
      run: jb install
    - name: Compile manifests
      shell: bash
      working-directory: clusters/
      run: |
        tk export ${{ inputs.cluster }}/compiled ${{ inputs.cluster }} --merge-strategy=replace-envs
    - name: Sanitize names
      shell: bash
      working-directory: clusters/
      run: |
        find . -depth -name '*:*' -execdir bash -c 'mv "$1" "${1//:/}"' bash {} \;
        find . -depth -name manifest.json -print0 | xargs -0 -I {} sh -c "jq 'with_entries(.key |= (strings | gsub(\":\"; \"\")))' {} > tmp.json && mv tmp.json {}"
    - name: Store manifests
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
      with:
        name: manifests-${{ inputs.cluster }}
        path: clusters/${{ inputs.cluster }}/compiled
