name: "Clusters: Compile manifests"
# TODO: this currently only runs when a cluster specification is changed. It does not run when something in `lib/`
# is updated. On `lib/` update, all clusters using that library should be recompiled.
on:
  push:
    branches:
      - main
    paths:
      - clusters/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changed-clusters:
    name: Detect changed files
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    outputs:
      changed-clusters: ${{ steps.collect-envs.outputs.changed-clusters }}
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Check for file changes
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: changes
        with:
          list-files: json
          filters: .github/filters.yml

      - name: Collect changed environments
        id: collect-envs
        if: |
          steps.changes.outputs.clusters_tanka == 'true'
        shell: bash
        run: |
          PATHS='${{ steps.changes.outputs.clusters_tanka_files }}'
          OUTPUT=$(echo $PATHS | jq --raw-output -c 'map(. |= split("/") | { "cluster": .[1], "env": .[2]})')
          echo "changed-clusters=${OUTPUT}" >> $GITHUB_OUTPUT

  compile:
    name: Compile
    needs:
      - changed-clusters
    if: ${{ needs.changed-clusters.outputs.changed-clusters }}
    strategy:
      matrix:
        cluster:
          ["${{ fromJson(needs.changed-clusters.outputs.changed-clusters) }}"]
      fail-fast: false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: clusters/
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Setup Jsonnet
        uses: kobtea/setup-jsonnet-action@1ba74f3571a59047dd4c5b8cb365bd3656f88e2a # v1
      # TODO: make this a proper action
      - name: Setup Tanka
        run: |
          curl -L https://github.com/grafana/tanka/releases/download/v0.25.0/tk-linux-amd64 --output ${{ github.action_path }}/tk
          chmod +x ${{ github.action_path }}/tk
          echo ${{ github.action_path }} >> $GITHUB_PATH
      - name: Install dependencies
        working-directory: clusters/
        run: jb install
      - name: Compile manifests
        working-directory: clusters/
        run: |
          mkdir -p ${{ matrix.cluster.cluster}}/compiled/${{ matrix.cluster.env }}
          tk export ${{ matrix.cluster.cluster}}/compiled/${{ matrix.cluster.env }} ${{ matrix.cluster.cluster}}/${{ matrix.cluster.env }} --merge-strategy replace-envs
      - name: Push manifests
        run: |
          git config --global user.name "actions[bot]"
          git config --global user.email "actions@colorful-pandas.com"
          # NOTE: this might lead to race conditions if multiple environments are updated at once
          git pull --ff-only
          git add ${{ matrix.cluster.cluster}}/compiled/${{ matrix.cluster.env }}/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update cluster manifests for ${{ matrix.cluster.cluster}}/${{ matrix.cluster.env }}"
          git push
