name: "Clusters: Compile manifests"
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changed-clusters:
    name: Detect changed files
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    outputs:
      changed-clusters: ${{ steps.collect-clusters.outputs.changed-clusters }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check for file changes
        uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          list-files: json
          filters: .github/filters.yml

      - name: Collect changed clusters
        id: collect-clusters
        if: |
          steps.changes.outputs.clusters_tanka == 'true'
        shell: bash
        run: |
          PATHS='${{ steps.changes.outputs.clusters_tanka_files }}'
          OUTPUT=$(echo $PATHS | jq --raw-output -c 'map(. |= split("/") | { "cluster": .[1], "env": .[2]})')
          echo "changed-clusters=${OUTPUT}" >> $GITHUB_OUTPUT

  compile:
    name: Compile
    needs:
      - changed-clusters
    if: ${{ needs.changed-clusters.outputs.changed-clusters }}
    strategy:
      matrix:
        cluster:
          ["${{ fromJson(needs.changed-clusters.outputs.changed-clusters) }}"]
      fail-fast: false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: clusters/
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - name: Setup Jsonnet
        uses: kobtea/setup-jsonnet-action@v1
      # TODO: make this a proper action
      - name: Setup Tanka
        run: |
          curl -L https://github.com/grafana/tanka/releases/download/v0.25.0/tk-linux-amd64 --output tk
          chmod +x tk
      - name: Install dependencies
        run: jb install
      - name: Compile manifests
        run: |
          mkdir -p ${{ matrix.cluster.cluster}}/${{ matrix.cluster.env }}-compiled
          ./tk export ${{ matrix.cluster.cluster}}/compiled/${{ matrix.cluster.env }} ${{ matrix.cluster.cluster}}/${{ matrix.cluster.env }} --merge-strategy replace-envs
      - name: Push manifests
        run: |
          git add ${{ matrix.cluster.cluster}}/compiled/${{ matrix.cluster.env }}/
          git config --global user.name "actions[bot]"
          git config --global user.email "actions@colorful-pandas.com"
          # NOTE: this might lead to race conditions if multiple environments are updated at once
          git pull --ff-only
          git commit -am "Update cluster manifests for ${{ matrix.cluster.cluster}}/${{ matrix.cluster.env }}"
          git push
