name: "Compile platform"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - clusters/lib/**
      - clusters/platform/**
      - "!clusters/platform/compiled"
  workflow_call:
    secrets:
      APP_ID:
        required: true
      APP_KEY:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  detect-changes:
    name: Detect changed files
    runs-on: ubuntu-22.04
    outputs:
      changes: ${{ steps.changes.outputs.tanka }}
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Check for file changes
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: changes
        with:
          list-files: json
          filters: .github/filters.yml

  compile:
    name: Compile
    needs:
      - detect-changes
    if: needs.detect-changes.outputs.changes == 'true'
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Get tool versions
        id: tool-versions
        run: |
          echo "tanka-version=$(awk '/^tanka / { print $2 }' .tool-versions)" >> $GITHUB_OUTPUT
          echo "helm-version=$(awk '/^helm / { print $2 }' .tool-versions)" >> $GITHUB_OUTPUT

      - name: Compile Kubernetes manifests
        uses: ./.github/actions/compile-environments
        with:
          cluster: platform
          tanka-version: ${{ steps.tool-versions.outputs.tanka-version }}
          helm-version: ${{ steps.tool-versions.outputs.helm-version }}

      - name: Get app token
        id: get-token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_KEY }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.get-token.outputs.token }}
          commit-message: Update `platform` manifests
          author: "astronaut-panda[bot] <137164246+astronaut-panda[bot]@users.noreply.github.com>"
          branch: actions/compile-clusters
          title: Update `platform` manifests
          body: Update `platform` manifests
          labels: |
            ops
            platform
