name: Add platform manifest changes to PR
on:
  workflow_dispatch:
  pull_request:
    paths:
      - clusters/lib/**
      - clusters/platform/**
      - "!clusters/platform/compiled/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  compile-platform:
    name: Compile platform manifests and comment diff in PR
    runs-on: ubuntu-22.04
    steps:
      - name: Get app token
        id: app-token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_KEY }}

      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Get tool versions
        id: tool-versions
        uses: marocchino/tool-versions-action@608d0ecb8f01e467223f0a854ead7d3fc784b540 # v1

      - name: Setup Earthly
        uses: earthly/actions-setup@v1
        with:
          version: v${{ steps.tool-versions.outputs.earthly }}

      - name: Compile Kubernetes manifests
        run: earthly --org panda-den --sat github-actions --no-output +compile-cluster-manifests --CLUSTER=platform
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}

      - name: Get diff
        id: diff
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "diff<<$EOF" >> $GITHUB_OUTPUT
          echo "$(git diff | sed 's/`/#/g' | sed 's/#/\\`/g')" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Update PR
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('compiled platform manifests')
            });
            const output = `#### This pull request will change the compiled platform manifests as follows:
            \`\`\`diff
            ${{ steps.diff.outputs.diff }}
            \`\`\`
            `;
            // 3. Delete previous comment so PR timeline makes sense
            if (botComment) {
              github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
              });
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
