name: Compile platform manifests and create pull request
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - clusters/lib/
      - clusters/platform/
      - "!clusters/platform/compiled/"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-condition:
    name: Check whether workflow should run
    runs-on: ubuntu-22.04
    outputs:
      changes: ${{ steps.changes.outputs.compile-platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Check for file changes
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: changes
        with:
          list-files: json
          filters: .github/filters.yml

  compile-platform:
    name: Compile platform manifests and create pull request
    needs:
      - check-condition
    if: needs.check-condition.outputs.changes == 'true'
    runs-on: ubuntu-22.04
    steps:
      - name: Get app token
        id: app-token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_KEY }}

      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Get tool versions
        id: tool-versions
        uses: marocchino/tool-versions-action@608d0ecb8f01e467223f0a854ead7d3fc784b540 # v1

      - name: Compile Kubernetes manifests
        uses: ./.github/actions/compile-environments
        with:
          cluster: platform
          tanka-version: ${{ steps.tool-versions.outputs.tanka }}
          helm-version: ${{ steps.tool-versions.outputs.helm }}

      - name: Create pull request
        id: create-pr
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: Update `platform` manifests
          author: "astronaut-panda[bot] <137164246+astronaut-panda[bot]@users.noreply.github.com>"
          branch: actions/compile-clusters
          title: Update `platform` manifests
          body: Update `platform` manifests
          labels: |
            ops
            platform

      - name: Set pull request to auto-merge
        run: gh pr merge --squash --auto "${{ steps.create-pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
