name: Build Colorful Pandas image, create pull request and set to auto-merge
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-condition:
    name: Check whether workflow should run
    runs-on: buildjet-2vcpu-ubuntu-2204
    outputs:
      changes: ${{ steps.changes.outputs.deploy-colorful-pandas }}
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Check for file changes
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: changes
        with:
          list-files: json
          filters: .github/filters.yml

  deploy-colorful-pandas:
    name: Build Colorful Pandas image, create pull request and set to auto-merge
    needs:
      - check-condition
    if: needs.check-condition.outputs.changes == 'true'
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - name: Get app token
        id: app-token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_KEY }}

      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@16c0bc4a6e6ada2cfd8afd41d22d95379cf7c32a # v2

      - name: Log into GHCR
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set environment
        run: echo "VERSION=$(date '+%y.%-m.%-d')-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4
        with:
          platforms: linux/arm64
          context: colorful-pandas/
          file: colorful-pandas/deploy/Dockerfile
          tags: ghcr.io/panda-den/colorful-pandas:latest,ghcr.io/panda-den/colorful-pandas:${{ env.VERSION }}
          push: true
          cache-from: type=registry,ref=ghcr.io/panda-den/colorful-pandas:buildcache
          cache-to: type=registry,ref=ghcr.io/panda-den/colorful-pandas:buildcache,mode=max

      - name: Update image tag
        run: |
          sed -i "s/colorfulPandas: 'ghcr\.io\/panda-den\/colorful-pandas:\(.*\)'/colorfulPandas: 'ghcr.io\/panda-den\/colorful-pandas:${{ env.VERSION }}'/g" clusters/platform/default/colorful-pandas.jsonnet

      - name: Create pull request
        id: create-pr
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5
        with:
          token: ${{ steps.app-token.outputs.token }}
          add-paths: |
            clusters/platform/default/colorful-pandas.jsonnet
          commit-message: Update Colorful Pandas to v${{ env.VERSION }}
          author: "astronaut-panda[bot] <137164246+astronaut-panda[bot]@users.noreply.github.com>"
          branch: actions/deploy-colorful-pandas
          title: Update Colorful Pandas to v${{ env.VERSION }}
          body: Update Colorful Pandas to v${{ env.VERSION }}
          labels: |
            ops
            platform
            colorful-pandas

      - name: Set pull request to auto-merge
        run: gh pr merge --squash --auto "${{ steps.create-pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
