name: Deploy Colorful Pandas
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - colorful-pandas/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy-colorful-pandas:
    name: Build Colorful Pandas image, create pull request and set to auto-merge
    runs-on: ubuntu-22.04
    steps:
      - name: Get app token
        id: app-token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_KEY }}

      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Get tool versions
        id: tool-versions
        uses: marocchino/tool-versions-action@608d0ecb8f01e467223f0a854ead7d3fc784b540 # v1

      - name: Setup Earthly
        uses: earthly/actions-setup@v1
        with:
          version: v${{ steps.outputs.tool-versions.earthly }}

      - name: Log into GHCR
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version
        run: echo "VERSION=$(date '+%y.%-m.%-d')-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push image
        run: earthly --sat github-actions --push --no-output +deploy-colorful-pandas --VERSION=${{ env.VERSION }}

      - name: Update image tag
        run: |
          sed -i "s/colorfulPandas: 'ghcr\.io\/panda-den\/colorful-pandas:\(.*\)'/colorfulPandas: 'ghcr.io\/panda-den\/colorful-pandas:${{ env.VERSION }}'/g" clusters/platform/default/colorful-pandas.jsonnet

      - name: Create pull request
        id: create-pr
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5
        with:
          token: ${{ steps.app-token.outputs.token }}
          add-paths: |
            clusters/platform/default/colorful-pandas.jsonnet
          commit-message: Update Colorful Pandas to v${{ env.VERSION }}
          author: "astronaut-panda[bot] <137164246+astronaut-panda[bot]@users.noreply.github.com>"
          branch: actions/deploy-colorful-pandas
          title: Update Colorful Pandas to v${{ env.VERSION }}
          body: Update Colorful Pandas to v${{ env.VERSION }}
          labels: |
            ops
            platform
            colorful-pandas

      - name: Set pull request to auto-merge
        run: gh pr merge --squash --auto "${{ steps.create-pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
