name: Lint Colorful Pandas
on:
  push:
    branches:
      - renovate/**
  merge_group:
  pull_request:

env:
  MIX_ENV: test

jobs:
  check-condition:
    name: Check whether workflow should run
    runs-on: buildjet-2vcpu-ubuntu-2204
    outputs:
      changes: ${{ steps.changes.outputs.lint-colorful-pandas }}
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Check for file changes
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: changes
        with:
          list-files: json
          filters: .github/filters.yml

  compile:
    name: Compile
    needs:
      - check-condition
    if: needs.check-condition.outputs.changes == 'true'
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: buildjet/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        id: deps-cache
        with:
          path: |
            colorful-pandas/deps/
            colorful-pandas/_build/
          key: mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-
      - run: mix deps.get
        working-directory: colorful-pandas/
        if: steps.deps-cache.outputs.cache-hit != 'true'
      - run: mix deps.compile
        working-directory: colorful-pandas/
        if: steps.deps-cache.outputs.cache-hit != 'true'
      - run: mix compile --warnings-as-errors
        working-directory: colorful-pandas/

  lint:
    name: Lint
    runs-on: buildjet-2vcpu-ubuntu-2204
    needs: compile
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: buildjet/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: |
            colorful-pandas/deps/
            colorful-pandas/_build/
          key: mix-${{ github.sha }}
          restore-keys: |
            mix-${{ hashFiles('**/mix.lock') }}
      - run: mix deps.unlock --check-unused
        working-directory: colorful-pandas/
      - run: mix hex.audit
        working-directory: colorful-pandas/
      - run: mix format --check-formatted
        working-directory: colorful-pandas/
      - run: mix credo
        working-directory: colorful-pandas/
      - run: mix excellent_migrations.check_safety
        working-directory: colorful-pandas/
      - run: mix sobelow --config
        working-directory: colorful-pandas/
