name: Lint Colorful Pandas
on:
  merge_group:
  push:
    branches:
      - renovate/**
  pull_request:
    paths:
      - colorful-pandas/**

env:
  MIX_ENV: test

jobs:
  compile:
    name: Compile
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: buildjet/cache@e376f15c6ec6dc595375c78633174c7e5f92dc0e # v3
        id: deps-cache
        with:
          path: |
            colorful-pandas/deps/
            colorful-pandas/_build/
          key: mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-
      - run: mix deps.get
        working-directory: colorful-pandas/
        if: steps.deps-cache.outputs.cache-hit != 'true'
      - run: mix deps.compile
        working-directory: colorful-pandas/
        if: steps.deps-cache.outputs.cache-hit != 'true'
      - run: mix compile --warnings-as-errors
        working-directory: colorful-pandas/

  lint:
    name: Lint
    runs-on: buildjet-2vcpu-ubuntu-2204
    needs: compile
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: buildjet/cache@e376f15c6ec6dc595375c78633174c7e5f92dc0e # v3
        with:
          path: |
            colorful-pandas/deps/
            colorful-pandas/_build/
          key: mix-${{ github.sha }}
          restore-keys: |
            mix-${{ hashFiles('**/mix.lock') }}
      - run: mix deps.unlock --check-unused
        working-directory: colorful-pandas/
      - run: mix hex.audit
        working-directory: colorful-pandas/
      - run: mix format --check-formatted
        working-directory: colorful-pandas/
      - run: mix credo
        working-directory: colorful-pandas/
      - run: mix excellent_migrations.check_safety
        working-directory: colorful-pandas/
      - run: mix sobelow --config
        working-directory: colorful-pandas/
