name: Renovate
on:
  push:
  schedule:
    - cron: '0/15 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Renovate
        uses: renovatebot/github-action@v38.1.6
        with:
          configurationFile: ./.github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
