name: Renovate
on:
  push:
  schedule:
    - cron: "0 5 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_APP_KEY }}
      - name: Renovate
        uses: renovatebot/github-action@v38.1.6
        with:
          configurationFile: ./.github/renovate.json
          token: ${{ steps.get_token.outputs.token }}
