name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get app token
        id: get_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_KEY }}

      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          token: ${{ steps.get_token.outputs.token }}

      - name: Run Renovate
        uses: renovatebot/github-action@96a5122bb4c10a5b16d944b3a27398c5d75d2064 # v38.1.9
        with:
          configurationFile: ./.github/renovate.json
          token: ${{ steps.get_token.outputs.token }}
