name: Test Colorful Pandas
on:
  merge_group:
  pull_request:
    paths:
      - colorful-pandas/**

env:
  MIX_ENV: test

jobs:
  compile:
    name: Compile
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        id: deps-cache
        with:
          path: |
            colorful-pandas/deps/
            colorful-pandas/_build/
          key: mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-
      - run: mix deps.get
        working-directory: colorful-pandas/
        if: steps.deps-cache.outputs.cache-hit != 'true'
      - run: mix deps.compile
        working-directory: colorful-pandas/
        if: steps.deps-cache.outputs.cache-hit != 'true'
      - run: mix compile --warnings-as-errors
        working-directory: colorful-pandas/

  test:
    name: Test
    needs: compile
    runs-on: buildjet-2vcpu-ubuntu-2204
    env:
      POSTGRES_HOST: localhost
    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: |
            colorful-pandas/deps/
            colorful-pandas/_build/
          key: mix-${{ github.sha }}
          restore-keys: |
            mix-${{ hashFiles('**/mix.lock') }}
      - run: mix ecto.drop
        working-directory: colorful-pandas/
      - run: mix ecto.create
        working-directory: colorful-pandas/
      - run: mix ecto.migrate
        working-directory: colorful-pandas/
      - run: mix test
        working-directory: colorful-pandas/
