name: Test Colorful Pandas
on:
  push:
    branches:
      - renovate/**
    paths:
      - colorful-pandas/**
  pull_request:
    paths:
      - colorful-pandas/**
  merge_group:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Setup Earthly
        uses: earthly/actions-setup@v1
        with:
          version: v0.7.11

      - name: Run Earthly
        run: earthly --org panda-den --sat test-colorful-pandas -P --ci +test-colorful-pandas
