name: Test
on:
  merge_group:
  pull_request:
  push:
    branches:
      - renovate/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  playwright:
    name: Playwright
    runs-on: buildjet-2vcpu-ubuntu-2204
    env:
      POSTGRES_HOST: localhost
    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Setup node
        uses: buildjet/setup-node@c7d4af42cfb6551248967ed0e51379dbae4cdefd # v3
        with:
          node-version-file: .tool-versions

      - name: Setup BEAM
        uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Cache Playwright binaries
        uses: buildjet/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        id: playwright-cache
        with:
          key: playwright
          path: |
            ~/.cache/ms-playwright

      - name: Install dependencies
        run: npm ci
        working-directory: integration-tests/

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: integration-tests/

      - name: Start Colorful Pandas
        uses: BerniWittmann/background-server-action@v1
        with:
          command: npx --prefix integration-tests/ playwright test
          start: cd colorful-pandas && mix phx.server
          wait-on: 'http://localhost:4000'

      - name: Run tests
        run: npx playwright test
        working-directory: integration-tests/

      - name: Upload report
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        if: always()
        with:
          name: playwright-report
          path: integration-tests/playwright-report/
          retention-days: 30
