name: Test Colorful Pandas
on:
  push:
    branches:
      - renovate/**
  pull_request:
  merge_group:

env:
  MIX_ENV: test

jobs:
  check-condition:
    name: Check whether workflow should run
    runs-on: ubuntu-22.04
    outputs:
      changes: ${{ steps.changes.outputs.test-colorful-pandas }}
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Check for file changes
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: changes
        with:
          list-files: json
          filters: .github/filters.yml

  compile:
    name: Compile
    needs:
      - check-condition
    if: needs.check-condition.outputs.changes == 'true'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Setup BEAM
        uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        id: deps-cache
        with:
          path: |
            colorful-pandas/deps/
            colorful-pandas/_build/
          key: mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-

      - name: Get dependencies
        if: steps.deps-cache.outputs.cache-hit != 'true'
        working-directory: colorful-pandas/
        run: mix deps.get

      - name: Compile dependencies
        if: steps.deps-cache.outputs.cache-hit != 'true'
        working-directory: colorful-pandas/
        run: mix deps.compile

      - name: Compile project
        working-directory: colorful-pandas/
        run: mix compile --warnings-as-errors

  lint:
    name: Lint Colorful Pandas
    runs-on: ubuntu-22.04
    needs: compile
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Setup BEAM
        uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: |
            colorful-pandas/deps/
            colorful-pandas/_build/
          key: mix-${{ github.sha }}
          restore-keys: |
            mix-${{ hashFiles('**/mix.lock') }}

      - name: Check for unused dependencies
        working-directory: colorful-pandas/
        run: mix deps.unlock --check-unused

      - name: Check for deprecated dependencies
        working-directory: colorful-pandas/
        run: mix hex.audit

      - name: Check formatting
        working-directory: colorful-pandas/
        run: mix format --check-formatted

      - name: Run Credo
        working-directory: colorful-pandas/
        run: mix credo

      - name: Check migrations
        working-directory: colorful-pandas/
        run: mix excellent_migrations.check_safety

      - name: Run static analysis
        working-directory: colorful-pandas/
        run: mix sobelow --config

  test:
    name: Test Colorful Pandas
    needs: compile
    runs-on: ubuntu-22.04
    env:
      POSTGRES_HOST: localhost
    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Setup BEAM
        uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        id: deps-cache
        with:
          path: |
            colorful-pandas/deps/
            colorful-pandas/_build/
          key: mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-

      - name: Drop database
        working-directory: colorful-pandas/
        run: mix ecto.drop

      - name: Create database
        working-directory: colorful-pandas/
        run: mix ecto.create

      - name: Run migrations
        working-directory: colorful-pandas/
        run: mix ecto.migrate

      - name: Run tests
        working-directory: colorful-pandas/
        run: mix test

  playwright:
    name: Playwright
    runs-on: ubuntu-22.04
    needs: compile
    env:
      POSTGRES_HOST: localhost
    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version-file: .tool-versions

      - name: Setup BEAM
        uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: |
            colorful-pandas/deps/
            colorful-pandas/_build/
          key: mix-${{ github.sha }}
          restore-keys: |
            mix-${{ hashFiles('**/mix.lock') }}

      # - name: Cache Playwright binaries
      #   uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
      #   id: playwright-cache
      #   with:
      #     key: playwright
      #     path: |
      #       ~/.cache/ms-playwright
      #
      # - name: Install dependencies
      #   run: npm ci
      #   working-directory: integration-tests/
      #
      # - name: Install Playwright browsers
      #   run: npx playwright install --with-deps
      #   working-directory: integration-tests/
      #
      # - name: Start Colorful Pandas
      #   uses: BerniWittmann/background-server-action@v1
      #   with:
      #     command: npx --prefix integration-tests/ playwright test
      #     start: cd colorful-pandas && mix phx.server
      #     wait-on: 'http://localhost:4000'
      #
      # - name: Run tests
      #   run: npx playwright test
      #   working-directory: integration-tests/
      #
      # - name: Upload report
      #   uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: integration-tests/playwright-report/
      #     retention-days: 30
